USE [master]
GO
ALTER DATABASE [STG] SET SINGLE_USER  WITH ROLLBACK IMMEDIATE 
ALTER DATABASE [STG]  MODIFY NAME = STGBKP
ALTER DATABASE [STGBKP] SET MULTI_USER  WITH ROLLBACK IMMEDIATE 


USE [master]
GO
ALTER DATABASE [ODS] SET SINGLE_USER  WITH ROLLBACK IMMEDIATE 
ALTER DATABASE [ODS]  MODIFY NAME = ODSBKP
ALTER DATABASE [ODSBKP] SET MULTI_USER  WITH ROLLBACK IMMEDIATE 


USE [master]
GO
ALTER DATABASE [EDW] SET SINGLE_USER  WITH ROLLBACK IMMEDIATE 
ALTER DATABASE [EDW]  MODIFY NAME = EDWBKP
ALTER DATABASE [EDWBKP] SET MULTI_USER  WITH ROLLBACK IMMEDIATE 


USE [master]
GO
ALTER DATABASE [STGUPG] SET SINGLE_USER  WITH ROLLBACK IMMEDIATE 
ALTER DATABASE [STGUPG]  MODIFY NAME = STG
ALTER DATABASE [STG] SET MULTI_USER  WITH ROLLBACK IMMEDIATE 




USE [master]
GO
ALTER DATABASE [ODSUPG] SET SINGLE_USER  WITH ROLLBACK IMMEDIATE 
ALTER DATABASE [ODSUPG]  MODIFY NAME = ODS
ALTER DATABASE [ODS] SET MULTI_USER  WITH ROLLBACK IMMEDIATE 


USE [master]
GO
ALTER DATABASE [EDWUPG] SET SINGLE_USER  WITH ROLLBACK IMMEDIATE 
ALTER DATABASE [EDWUPG]  MODIFY NAME = EDW
ALTER DATABASE [EDW] SET MULTI_USER  WITH ROLLBACK IMMEDIATE 

