=============================Create User Scripts to be executed:=============================
Use [ET1] IF NOT EXISTS (SELECT 1 FROM [ET1].sys.database_principals WHERE name = 'dbo') CREATE USER [dbo] FOR LOGIN [sa] WITH DEFAULT_SCHEMA = [dbo];
Use [ET1] IF NOT EXISTS (SELECT 1 FROM [ET1].sys.database_principals WHERE name = 'guest') CREATE USER [guest] WITH DEFAULT_SCHEMA = [guest];
Use [ET1] IF NOT EXISTS (SELECT 1 FROM [ET1].sys.database_principals WHERE name = 'INFORMATION_SCHEMA') CREATE USER [INFORMATION_SCHEMA];
Use [ET1] IF NOT EXISTS (SELECT 1 FROM [ET1].sys.database_principals WHERE name = 'sys') CREATE USER [sys];
Use [ET1] IF NOT EXISTS (SELECT 1 FROM [ET1].sys.database_principals WHERE name = 'BIReader') CREATE USER [BIReader] FOR LOGIN [BIReader] WITH DEFAULT_SCHEMA = [dbo];
Use [ET1] IF NOT EXISTS (SELECT 1 FROM [ET1].sys.database_principals WHERE name = 'NUVASIVE\AtlasAdministrators') CREATE USER [NUVASIVE\AtlasAdministrators] FOR LOGIN [NUVASIVE\AtlasAdministrators];
Use [ET1] IF NOT EXISTS (SELECT 1 FROM [ET1].sys.database_principals WHERE name = 'NUVASIVE\AtlasContractors') CREATE USER [NUVASIVE\AtlasContractors] FOR LOGIN [NUVASIVE\AtlasContractors];
Use [ET1] IF NOT EXISTS (SELECT 1 FROM [ET1].sys.database_principals WHERE name = 'NUVASIVE\AtlasDevelopers') CREATE USER [NUVASIVE\AtlasDevelopers] FOR LOGIN [NUVASIVE\AtlasDevelopers];
Use [ET1] IF NOT EXISTS (SELECT 1 FROM [ET1].sys.database_principals WHERE name = 'NUVASIVE\svc_acc_dev') CREATE USER [NUVASIVE\svc_acc_dev] FOR LOGIN [NUVASIVE\svc_acc_dev] WITH DEFAULT_SCHEMA = [dbo];
Use [ET1] IF NOT EXISTS (SELECT 1 FROM [ET1].sys.database_principals WHERE name = '_npSSISUser') CREATE USER [_npSSISUser] FOR LOGIN [_npSSISUser] WITH DEFAULT_SCHEMA = [dbo];
Use [ET1] IF NOT EXISTS (SELECT 1 FROM [ET1].sys.database_principals WHERE name = 'et1') CREATE USER [et1] FOR LOGIN [et1] WITH DEFAULT_SCHEMA = [et1];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'dbo') CREATE USER [dbo] FOR LOGIN [sa] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'guest') CREATE USER [guest] WITH DEFAULT_SCHEMA = [guest];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'INFORMATION_SCHEMA') CREATE USER [INFORMATION_SCHEMA];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'sys') CREATE USER [sys];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'BIReader') CREATE USER [BIReader] FOR LOGIN [BIReader] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'BIUSER1') CREATE USER [BIUSER1] FOR LOGIN [BIUSER1] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\AtlasAdministrators') CREATE USER [NUVASIVE\AtlasAdministrators] FOR LOGIN [NUVASIVE\AtlasAdministrators];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\AtlasContractors') CREATE USER [NUVASIVE\AtlasContractors] FOR LOGIN [NUVASIVE\AtlasContractors];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\AtlasDataReaders') CREATE USER [NUVASIVE\AtlasDataReaders] FOR LOGIN [NUVASIVE\AtlasDataReaders];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\AtlasDevelopers') CREATE USER [NUVASIVE\AtlasDevelopers] FOR LOGIN [NUVASIVE\AtlasDevelopers];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\IT_Atlas_Admin') CREATE USER [NUVASIVE\IT_Atlas_Admin] FOR LOGIN [NUVASIVE\IT_Atlas_Admin];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\LV_SAPSQLP3_Read') CREATE USER [NUVASIVE\LV_SAPSQLP3_Read];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\aingold') CREATE USER [NUVASIVE\aingold] FOR LOGIN [NUVASIVE\aingold] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\jbertolini') CREATE USER [NUVASIVE\jbertolini] FOR LOGIN [NUVASIVE\jbertolini] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\svc_acc_dev') CREATE USER [NUVASIVE\svc_acc_dev] FOR LOGIN [NUVASIVE\svc_acc_dev] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\svc_acc_prd') CREATE USER [NUVASIVE\svc_acc_prd] FOR LOGIN [NUVASIVE\svc_acc_prd] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\svc_acc_qa') CREATE USER [NUVASIVE\svc_acc_qa] FOR LOGIN [NUVASIVE\svc_acc_qa] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\svc_octopus') CREATE USER [NUVASIVE\svc_octopus] FOR LOGIN [NUVASIVE\svc_octopus] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = 'NUVASIVE\svc_tfs_agent') CREATE USER [NUVASIVE\svc_tfs_agent] FOR LOGIN [NUVASIVE\svc_tfs_agent] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = '_SSISUser') CREATE USER [_SSISUser] FOR LOGIN [_SSISUser] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = '_SSIS_ACC_SetRetrieval') CREATE USER [_SSIS_ACC_SetRetrieval] FOR LOGIN [_SSIS_ACC_SetRetrieval] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = '_acc_reader') CREATE USER [_acc_reader] FOR LOGIN [_acc_reader] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = '_acc_user') CREATE USER [_acc_user] FOR LOGIN [_acc_user] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = '_atlas_reporting') CREATE USER [_atlas_reporting] FOR LOGIN [_atlas_reporting] WITH DEFAULT_SCHEMA = [dbo];
Use [ACC_ET1] IF NOT EXISTS (SELECT 1 FROM [ACC_ET1].sys.database_principals WHERE name = '_svc_sapacc_prd') CREATE USER [_svc_sapacc_prd] FOR LOGIN [_svc_sapacc_prd] WITH DEFAULT_SCHEMA = [dbo];
--36 DB Users scripted
=============================END: Create User Scripts to be executed:=============================
		
=============================Add RoleMember Scripts to be executed:=============================
USE [ET1] EXEC sp_addrolemember 'db_owner', 'et1';
USE [ET1] EXEC sp_addrolemember 'db_datareader', 'BIReader';
USE [ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\AtlasAdministrators';
USE [ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\AtlasContractors';
USE [ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\AtlasDevelopers';
USE [ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\svc_acc_dev';
USE [ET1] EXEC sp_addrolemember 'db_datareader', '_npSSISUser';
USE [ACC_ET1] EXEC sp_addrolemember 'db_executor', 'NUVASIVE\AtlasAdministrators';
USE [ACC_ET1] EXEC sp_addrolemember 'db_executor', 'NUVASIVE\AtlasContractors';
USE [ACC_ET1] EXEC sp_addrolemember 'db_executor', 'NUVASIVE\AtlasDevelopers';
USE [ACC_ET1] EXEC sp_addrolemember 'db_executor', 'NUVASIVE\IT_Atlas_Admin';
USE [ACC_ET1] EXEC sp_addrolemember 'db_executor', 'NUVASIVE\svc_acc_dev';
USE [ACC_ET1] EXEC sp_addrolemember 'db_executor', 'NUVASIVE\svc_acc_prd';
USE [ACC_ET1] EXEC sp_addrolemember 'db_executor', 'NUVASIVE\svc_acc_qa';
USE [ACC_ET1] EXEC sp_addrolemember 'db_executor', 'NUVASIVE\svc_tfs_agent';
USE [ACC_ET1] EXEC sp_addrolemember 'db_executor', '_acc_reader';
USE [ACC_ET1] EXEC sp_addrolemember 'db_executor', '_atlas_reporting';
USE [ACC_ET1] EXEC sp_addrolemember 'db_executor', '_svc_sapacc_prd';
USE [ACC_ET1] EXEC sp_addrolemember 'aspnet_Membership_BasicAccess', 'aspnet_Membership_FullAccess';
USE [ACC_ET1] EXEC sp_addrolemember 'aspnet_Membership_ReportingAccess', 'aspnet_Membership_FullAccess';
USE [ACC_ET1] EXEC sp_addrolemember 'aspnet_Profile_BasicAccess', 'aspnet_Profile_FullAccess';
USE [ACC_ET1] EXEC sp_addrolemember 'aspnet_Profile_ReportingAccess', 'aspnet_Profile_FullAccess';
USE [ACC_ET1] EXEC sp_addrolemember 'aspnet_Roles_FullAccess', 'NUVASIVE\svc_acc_prd';
USE [ACC_ET1] EXEC sp_addrolemember 'aspnet_Roles_BasicAccess', 'NUVASIVE\svc_acc_prd';
USE [ACC_ET1] EXEC sp_addrolemember 'aspnet_Roles_BasicAccess', 'aspnet_Roles_FullAccess';
USE [ACC_ET1] EXEC sp_addrolemember 'aspnet_Roles_ReportingAccess', 'NUVASIVE\svc_acc_prd';
USE [ACC_ET1] EXEC sp_addrolemember 'aspnet_Roles_ReportingAccess', 'aspnet_Roles_FullAccess';
USE [ACC_ET1] EXEC sp_addrolemember 'aspnet_Personalization_BasicAccess', 'aspnet_Personalization_FullAccess';
USE [ACC_ET1] EXEC sp_addrolemember 'aspnet_Personalization_ReportingAccess', 'aspnet_Personalization_FullAccess';
USE [ACC_ET1] EXEC sp_addrolemember 'db_owner', 'NUVASIVE\AtlasAdministrators';
USE [ACC_ET1] EXEC sp_addrolemember 'db_owner', 'NUVASIVE\jbertolini';
USE [ACC_ET1] EXEC sp_addrolemember 'db_owner', '_acc_reader';
USE [ACC_ET1] EXEC sp_addrolemember 'db_owner', '_acc_user';
USE [ACC_ET1] EXEC sp_addrolemember 'db_ddladmin', 'NUVASIVE\AtlasAdministrators';
USE [ACC_ET1] EXEC sp_addrolemember 'db_ddladmin', 'NUVASIVE\AtlasDevelopers';
USE [ACC_ET1] EXEC sp_addrolemember 'db_ddladmin', 'NUVASIVE\aingold';
USE [ACC_ET1] EXEC sp_addrolemember 'db_ddladmin', 'NUVASIVE\svc_octopus';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', 'BIReader';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', 'BIUSER1';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\AtlasAdministrators';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\AtlasContractors';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\AtlasDataReaders';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\AtlasDevelopers';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\IT_Atlas_Admin';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\svc_acc_dev';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\svc_acc_prd';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\svc_acc_qa';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\svc_octopus';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', 'NUVASIVE\svc_tfs_agent';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', '_acc_reader';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', '_atlas_reporting';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datareader', '_svc_sapacc_prd';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datawriter', 'NUVASIVE\AtlasAdministrators';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datawriter', 'NUVASIVE\AtlasContractors';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datawriter', 'NUVASIVE\AtlasDevelopers';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datawriter', 'NUVASIVE\IT_Atlas_Admin';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datawriter', 'NUVASIVE\svc_acc_dev';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datawriter', 'NUVASIVE\svc_acc_prd';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datawriter', 'NUVASIVE\svc_acc_qa';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datawriter', 'NUVASIVE\svc_octopus';
USE [ACC_ET1] EXEC sp_addrolemember 'db_datawriter', 'NUVASIVE\svc_tfs_agent';
--61 DB Roles scripted
=============================END: Add RoleMember Scripts to be executed:=============================
