

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[EKKO]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[EKKO](
	[MANDT] [varchar](3) NOT NULL,
	[EBELN] [varchar](10) NOT NULL,
	[BUKRS] [varchar](4) NOT NULL,
	[BSTYP] [varchar](1) NOT NULL,
	[BSART] [varchar](4) NOT NULL,
	[BSAKZ] [varchar](1) NOT NULL,
	[LOEKZ] [varchar](1) NOT NULL,
	[STATU] [varchar](1) NOT NULL,
	[AEDAT] [varchar](8) NOT NULL,
	[ERNAM] [varchar](12) NOT NULL,
	[PINCR] [varchar](5) NOT NULL,
	[LPONR] [varchar](5) NOT NULL,
	[LIFNR] [varchar](10) NOT NULL,
	[SPRAS] [varchar](1) NOT NULL,
	[ZTERM] [varchar](4) NOT NULL,
	[ZBD1T] [decimal](3, 0) NOT NULL,
	[ZBD2T] [decimal](3, 0) NOT NULL,
	[ZBD3T] [decimal](3, 0) NOT NULL,
	[ZBD1P] [decimal](5, 3) NOT NULL,
	[ZBD2P] [decimal](5, 3) NOT NULL,
	[EKORG] [varchar](4) NOT NULL,
	[EKGRP] [varchar](3) NOT NULL,
	[WAERS] [varchar](5) NOT NULL,
	[WKURS] [decimal](9, 5) NOT NULL,
	[KUFIX] [varchar](1) NOT NULL,
	[BEDAT] [varchar](8) NOT NULL,
	[KDATB] [varchar](8) NOT NULL,
	[KDATE] [varchar](8) NOT NULL,
	[BWBDT] [varchar](8) NOT NULL,
	[ANGDT] [varchar](8) NOT NULL,
	[BNDDT] [varchar](8) NOT NULL,
	[GWLDT] [varchar](8) NOT NULL,
	[AUSNR] [varchar](10) NOT NULL,
	[ANGNR] [varchar](10) NOT NULL,
	[IHRAN] [varchar](8) NOT NULL,
	[IHREZ] [varchar](12) NOT NULL,
	[VERKF] [varchar](30) NOT NULL,
	[TELF1] [varchar](16) NOT NULL,
	[LLIEF] [varchar](10) NOT NULL,
	[KUNNR] [varchar](10) NOT NULL,
	[KONNR] [varchar](10) NOT NULL,
	[ABGRU] [varchar](2) NOT NULL,
	[AUTLF] [varchar](1) NOT NULL,
	[WEAKT] [varchar](1) NOT NULL,
	[RESWK] [varchar](4) NOT NULL,
	[LBLIF] [varchar](10) NOT NULL,
	[INCO1] [varchar](3) NOT NULL,
	[INCO2] [varchar](28) NOT NULL,
	[KTWRT] [decimal](15, 2) NOT NULL,
	[SUBMI] [varchar](10) NOT NULL,
	[KNUMV] [varchar](10) NOT NULL,
	[KALSM] [varchar](6) NOT NULL,
	[STAFO] [varchar](6) NOT NULL,
	[LIFRE] [varchar](10) NOT NULL,
	[EXNUM] [varchar](10) NOT NULL,
	[UNSEZ] [varchar](12) NOT NULL,
	[LOGSY] [varchar](10) NOT NULL,
	[UPINC] [varchar](5) NOT NULL,
	[STAKO] [varchar](1) NOT NULL,
	[FRGGR] [varchar](2) NOT NULL,
	[FRGSX] [varchar](2) NOT NULL,
	[FRGKE] [varchar](1) NOT NULL,
	[FRGZU] [varchar](8) NOT NULL,
	[FRGRL] [varchar](1) NOT NULL,
	[LANDS] [varchar](3) NOT NULL,
	[LPHIS] [varchar](1) NOT NULL,
	[ADRNR] [varchar](10) NOT NULL,
	[STCEG_L] [varchar](3) NOT NULL,
	[STCEG] [varchar](20) NOT NULL,
	[ABSGR] [varchar](2) NOT NULL,
	[ADDNR] [varchar](10) NOT NULL,
	[KORNR] [varchar](1) NOT NULL,
	[MEMORY] [varchar](1) NOT NULL,
	[PROCSTAT] [varchar](2) NOT NULL,
	[RLWRT] [decimal](15, 2) NOT NULL,
	[REVNO] [varchar](8) NOT NULL,
	[SCMPROC] [varchar](1) NOT NULL,
	[REASON_CODE] [varchar](4) NOT NULL,
	[FORCE_ID] [varchar](32) NOT NULL,
	[FORCE_CNT] [varchar](6) NOT NULL,
	[RELOC_ID] [varchar](10) NOT NULL,
	[RELOC_SEQ_ID] [varchar](4) NOT NULL,
	[POHF_TYPE] [varchar](1) NOT NULL,
	[EQ_EINDT] [varchar](8) NOT NULL,
	[EQ_WERKS] [varchar](4) NOT NULL,
	[FIXPO] [varchar](1) NOT NULL,
	[EKGRP_ALLOW] [varchar](1) NOT NULL,
	[WERKS_ALLOW] [varchar](1) NOT NULL,
	[CONTRACT_ALLOW] [varchar](1) NOT NULL,
	[PSTYP_ALLOW] [varchar](1) NOT NULL,
	[FIXPO_ALLOW] [varchar](1) NOT NULL,
	[KEY_ID_ALLOW] [varchar](1) NOT NULL,
	[AUREL_ALLOW] [varchar](1) NOT NULL,
	[DELPER_ALLOW] [varchar](1) NOT NULL,
	[EINDT_ALLOW] [varchar](1) NOT NULL,
	[OTB_LEVEL] [varchar](1) NOT NULL,
	[OTB_COND_TYPE] [varchar](4) NOT NULL,
	[KEY_ID] [varchar](16) NOT NULL,
	[OTB_VALUE] [decimal](17, 2) NOT NULL,
	[OTB_CURR] [varchar](5) NOT NULL,
	[OTB_RES_VALUE] [decimal](17, 2) NOT NULL,
	[OTB_SPEC_VALUE] [decimal](17, 2) NOT NULL,
	[SPR_RSN_PROFILE] [varchar](4) NOT NULL,
	[BUDG_TYPE] [varchar](2) NOT NULL,
	[OTB_STATUS] [varchar](1) NOT NULL,
	[OTB_REASON] [varchar](3) NOT NULL,
	[CHECK_TYPE] [varchar](1) NOT NULL,
	[CON_OTB_REQ] [varchar](1) NOT NULL,
	[CON_PREBOOK_LEV] [varchar](1) NOT NULL,
	[CON_DISTR_LEV] [varchar](1) NOT NULL,
 CONSTRAINT [PK_EKKO] PRIMARY KEY CLUSTERED 
(
	[MANDT] ASC,
	[EBELN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

SET ANSI_PADDING OFF
GO




IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[EQST]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[EQST](
	[MANDT] [varchar](3) NOT NULL,
	[EQUNR] [varchar](18) NOT NULL,
	[WERKS] [varchar](4) NOT NULL,
	[STLAN] [varchar](1) NOT NULL,
	[STLNR] [varchar](8) NOT NULL,
	[STLAL] [varchar](2) NOT NULL,
	[ANDAT] [varchar](8) NOT NULL,
	[ANNAM] [varchar](12) NOT NULL,
	[AEDAT] [varchar](8) NOT NULL,
	[AENAM] [varchar](12) NOT NULL
) ON [PRIMARY]
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[EQUI]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[EQUI](
	[MANDT] [varchar](3) NOT NULL,
	[EQUNR] [varchar](18) NOT NULL,
	[ERDAT] [varchar](8) NOT NULL,
	[ERNAM] [varchar](12) NOT NULL,
	[EQASP] [varchar](1) NOT NULL,
	[AEDAT] [varchar](8) NOT NULL,
	[AENAM] [varchar](12) NOT NULL,
	[BEGRU] [varchar](4) NOT NULL,
	[EQTYP] [varchar](1) NOT NULL,
	[EQART] [varchar](10) NOT NULL,
	[LVORM] [varchar](1) NOT NULL,
	[INVNR] [varchar](25) NOT NULL,
	[GROES] [varchar](18) NOT NULL,
	[BRGEW] [decimal](13, 3) NOT NULL,
	[GEWEI] [varchar](3) NOT NULL,
	[ANSDT] [varchar](8) NOT NULL,
	[ANSWT] [decimal](13, 2) NOT NULL,
	[WAERS] [varchar](5) NOT NULL,
	[ELIEF] [varchar](10) NOT NULL,
	[GWLEN] [varchar](8) NOT NULL,
	[GWLDT] [varchar](8) NOT NULL,
	[WDBWT] [decimal](13, 2) NOT NULL,
	[HERST] [varchar](30) NOT NULL,
	[HERLD] [varchar](3) NOT NULL,
	[HZEIN] [varchar](30) NOT NULL,
	[SERGE] [varchar](30) NOT NULL,
	[TYPBZ] [varchar](20) NOT NULL,
	[BAUJJ] [varchar](4) NOT NULL,
	[BAUMM] [varchar](2) NOT NULL,
	[APLKZ] [varchar](1) NOT NULL,
	[AULDT] [varchar](8) NOT NULL,
	[INBDT] [varchar](8) NOT NULL,
	[GERNR] [varchar](18) NOT NULL,
	[EQLFN] [varchar](3) NOT NULL,
	[GWLDV] [varchar](8) NOT NULL,
	[EQDAT] [varchar](8) NOT NULL,
	[EQBER] [varchar](30) NOT NULL,
	[EQNUM] [varchar](9) NOT NULL,
	[OBJNR] [varchar](22) NOT NULL,
	[EQSNR] [varchar](18) NOT NULL,
	[CUOBJ] [varchar](18) NOT NULL,
	[KRFKZ] [varchar](1) NOT NULL,
	[KMATN] [varchar](18) NOT NULL,
	[MATNR] [varchar](18) NOT NULL,
	[SERNR] [varchar](18) NOT NULL,
	[WERK] [varchar](4) NOT NULL,
	[LAGER] [varchar](4) NOT NULL,
	[CHARGE] [varchar](10) NOT NULL,
	[KUNDE] [varchar](10) NOT NULL,
	[WARPL] [varchar](12) NOT NULL,
	[IMRC_POINT] [varchar](12) NOT NULL,
	[REVLV] [varchar](2) NOT NULL,
	[MGANR] [varchar](20) NOT NULL,
	[BEGRUI] [varchar](1) NOT NULL,
	[S_EQUI] [varchar](1) NOT NULL,
	[S_SERIAL] [varchar](1) NOT NULL,
	[S_KONFI] [varchar](1) NOT NULL,
	[S_SALE] [varchar](1) NOT NULL,
	[S_FHM] [varchar](1) NOT NULL,
	[S_ELSE] [varchar](1) NOT NULL,
	[S_ISU] [varchar](1) NOT NULL,
	[S_EQBS] [varchar](1) NOT NULL,
	[S_FLEET] [varchar](1) NOT NULL,
	[BSTVP] [varchar](1) NOT NULL,
	[SPARTE] [varchar](2) NOT NULL,
	[HANDLE] [varchar](22) NOT NULL,
	[TSEGTP] [varchar](10) NOT NULL,
	[EMATN] [varchar](18) NOT NULL,
	[ACT_CHANGE_AA] [varchar](1) NOT NULL,
	[S_CC] [varchar](1) NOT NULL,
	[DATLWB] [varchar](8) NOT NULL,
	[/SOPROMET/VERSI] [varchar](12) NOT NULL,
	[VFDAT] [varchar](8) NOT NULL,
	[EQEXT_ACTIVE] [varchar](1) NOT NULL,
 CONSTRAINT [PK_EQUI] PRIMARY KEY CLUSTERED 
(
	[MANDT] ASC,
	[EQUNR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO



IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[LIKP]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[LIKP](
	[MANDT] [varchar](3) NOT NULL,
	[VBELN] [varchar](10) NOT NULL,
	[ERNAM] [varchar](12) NOT NULL,
	[ERZET] [varchar](6) NOT NULL,
	[ERDAT] [varchar](8) NOT NULL,
	[BZIRK] [varchar](6) NOT NULL,
	[VSTEL] [varchar](4) NOT NULL,
	[VKORG] [varchar](4) NOT NULL,
	[LFART] [varchar](4) NOT NULL,
	[AUTLF] [varchar](1) NOT NULL,
	[KZAZU] [varchar](1) NOT NULL,
	[WADAT] [varchar](8) NOT NULL,
	[LDDAT] [varchar](8) NOT NULL,
	[TDDAT] [varchar](8) NOT NULL,
	[LFDAT] [varchar](8) NOT NULL,
	[KODAT] [varchar](8) NOT NULL,
	[ABLAD] [varchar](25) NOT NULL,
	[INCO1] [varchar](3) NOT NULL,
	[INCO2] [varchar](28) NOT NULL,
	[EXPKZ] [varchar](1) NOT NULL,
	[ROUTE] [varchar](6) NOT NULL,
	[FAKSK] [varchar](2) NOT NULL,
	[LIFSK] [varchar](2) NOT NULL,
	[VBTYP] [varchar](1) NOT NULL,
	[KNFAK] [varchar](2) NOT NULL,
	[TPQUA] [varchar](1) NOT NULL,
	[TPGRP] [varchar](2) NOT NULL,
	[LPRIO] [varchar](2) NOT NULL,
	[VSBED] [varchar](2) NOT NULL,
	[KUNNR] [varchar](10) NOT NULL,
	[KUNAG] [varchar](10) NOT NULL,
	[KDGRP] [varchar](2) NOT NULL,
	[STZKL] [decimal](3, 2) NOT NULL,
	[STZZU] [decimal](3, 0) NOT NULL,
	[BTGEW] [decimal](15, 3) NOT NULL,
	[NTGEW] [decimal](15, 3) NOT NULL,
	[GEWEI] [varchar](3) NOT NULL,
	[VOLUM] [decimal](15, 3) NOT NULL,
	[VOLEH] [varchar](3) NOT NULL,
	[ANZPK] [varchar](5) NOT NULL,
	[BEROT] [varchar](20) NOT NULL,
	[LFUHR] [varchar](6) NOT NULL,
	[GRULG] [varchar](4) NOT NULL,
	[LSTEL] [varchar](2) NOT NULL,
	[TRAGR] [varchar](4) NOT NULL,
	[FKARV] [varchar](4) NOT NULL,
	[FKDAT] [varchar](8) NOT NULL,
	[PERFK] [varchar](2) NOT NULL,
	[ROUTA] [varchar](6) NOT NULL,
	[STAFO] [varchar](6) NOT NULL,
	[KALSM] [varchar](6) NOT NULL,
	[KNUMV] [varchar](10) NOT NULL,
	[WAERK] [varchar](5) NOT NULL,
	[VKBUR] [varchar](4) NOT NULL,
	[VBEAK] [decimal](6, 2) NOT NULL,
	[ZUKRL] [varchar](40) NOT NULL,
	[VERUR] [varchar](35) NOT NULL,
	[COMMN] [varchar](5) NOT NULL,
	[STWAE] [varchar](5) NOT NULL,
	[STCUR] [decimal](9, 5) NOT NULL,
	[EXNUM] [varchar](10) NOT NULL,
	[AENAM] [varchar](12) NOT NULL,
	[AEDAT] [varchar](8) NOT NULL,
	[LGNUM] [varchar](3) NOT NULL,
	[LISPL] [varchar](1) NOT NULL,
	[VKOIV] [varchar](4) NOT NULL,
	[VTWIV] [varchar](2) NOT NULL,
	[SPAIV] [varchar](2) NOT NULL,
	[FKAIV] [varchar](4) NOT NULL,
	[PIOIV] [varchar](2) NOT NULL,
	[FKDIV] [varchar](8) NOT NULL,
	[KUNIV] [varchar](10) NOT NULL,
	[KKBER] [varchar](4) NOT NULL,
	[KNKLI] [varchar](10) NOT NULL,
	[GRUPP] [varchar](4) NOT NULL,
	[SBGRP] [varchar](3) NOT NULL,
	[CTLPC] [varchar](3) NOT NULL,
	[CMWAE] [varchar](5) NOT NULL,
	[AMTBL] [decimal](15, 2) NOT NULL,
	[BOLNR] [varchar](35) NOT NULL,
	[LIFNR] [varchar](10) NOT NULL,
	[TRATY] [varchar](4) NOT NULL,
	[TRAID] [varchar](20) NOT NULL,
	[CMFRE] [varchar](8) NOT NULL,
	[CMNGV] [varchar](8) NOT NULL,
	[XABLN] [varchar](10) NOT NULL,
	[BLDAT] [varchar](8) NOT NULL,
	[WADAT_IST] [varchar](8) NOT NULL,
	[TRSPG] [varchar](2) NOT NULL,
	[TPSID] [varchar](5) NOT NULL,
	[LIFEX] [varchar](35) NOT NULL,
	[TERNR] [varchar](12) NOT NULL,
	[KALSM_CH] [varchar](6) NOT NULL,
	[KLIEF] [varchar](1) NOT NULL,
	[KALSP] [varchar](6) NOT NULL,
	[KNUMP] [varchar](10) NOT NULL,
	[NETWR] [decimal](15, 2) NOT NULL,
	[AULWE] [varchar](10) NOT NULL,
	[WERKS] [varchar](4) NOT NULL,
	[LCNUM] [varchar](10) NOT NULL,
	[ABSSC] [varchar](6) NOT NULL,
	[KOUHR] [varchar](6) NOT NULL,
	[TDUHR] [varchar](6) NOT NULL,
	[LDUHR] [varchar](6) NOT NULL,
	[WAUHR] [varchar](6) NOT NULL,
	[LGTOR] [varchar](3) NOT NULL,
	[LGBZO] [varchar](10) NOT NULL,
	[AKWAE] [varchar](5) NOT NULL,
	[AKKUR] [decimal](9, 5) NOT NULL,
	[AKPRZ] [decimal](5, 2) NOT NULL,
	[PROLI] [varchar](3) NOT NULL,
	[XBLNR] [varchar](25) NOT NULL,
	[HANDLE] [varchar](22) NOT NULL,
	[TSEGFL] [varchar](1) NOT NULL,
	[TSEGTP] [varchar](10) NOT NULL,
	[TZONIS] [varchar](6) NOT NULL,
	[TZONRC] [varchar](6) NOT NULL,
	[CONT_DG] [varchar](1) NOT NULL,
	[VERURSYS] [varchar](10) NOT NULL,
	[KZWAB] [varchar](1) NOT NULL,
	[VLSTK] [varchar](1) NOT NULL,
	[TCODE] [varchar](20) NOT NULL,
	[VSART] [varchar](2) NOT NULL,
	[TRMTYP] [varchar](18) NOT NULL,
	[SDABW] [varchar](4) NOT NULL,
	[VBUND] [varchar](6) NOT NULL,
	[XWOFF] [varchar](1) NOT NULL,
	[DIRTA] [varchar](1) NOT NULL,
	[PRVBE] [varchar](10) NOT NULL,
	[FOLAR] [varchar](4) NOT NULL,
	[PODAT] [varchar](8) NOT NULL,
	[POTIM] [varchar](6) NOT NULL,
	[VGANZ] [int] NOT NULL,
	[IMWRK] [varchar](1) NOT NULL,
	[SPE_LOEKZ] [varchar](1) NOT NULL,
	[SPE_LOC_SEQ] [varchar](3) NOT NULL,
	[SPE_ACC_APP_STS] [varchar](1) NOT NULL,
	[SPE_SHP_INF_STS] [varchar](1) NOT NULL,
	[SPE_RET_CANC] [varchar](1) NOT NULL,
	[SPE_WAUHR_IST] [varchar](6) NOT NULL,
	[SPE_WAZONE_IST] [varchar](6) NOT NULL,
	[SPE_REV_VLSTK] [varchar](1) NOT NULL,
	[SPE_LE_SCENARIO] [varchar](1) NOT NULL,
	[SPE_ORIG_SYS] [varchar](1) NOT NULL,
	[SPE_CHNG_SYS] [varchar](1) NOT NULL,
	[SPE_GEOROUTE] [varchar](10) NOT NULL,
	[SPE_GEOROUTEIND] [varchar](1) NOT NULL,
	[SPE_CARRIER_IND] [varchar](1) NOT NULL,
	[SPE_GTS_REL] [varchar](2) NOT NULL,
	[SPE_GTS_RT_CDE] [varchar](10) NOT NULL,
	[SPE_REL_TMSTMP] [decimal](15, 0) NOT NULL,
	[SPE_UNIT_SYSTEM] [varchar](10) NOT NULL,
	[SPE_INV_BFR_GI] [varchar](1) NOT NULL,
	[SPE_QI_STATUS] [varchar](1) NOT NULL,
	[SPE_RED_IND] [varchar](1) NOT NULL,
	[SAKES] [varchar](1) NOT NULL,
	[SPE_LIFEX_TYPE] [varchar](1) NOT NULL,
	[SPE_TTYPE] [varchar](10) NOT NULL,
	[SPE_PRO_NUMBER] [varchar](35) NOT NULL,
	[LOC_GUID] [varbinary](16) NULL,
	[/BEV1/LULEINH] [varchar](8) NOT NULL,
	[/BEV1/RPFAESS] [decimal](7, 0) NOT NULL,
	[/BEV1/RPKIST] [decimal](7, 0) NOT NULL,
	[/BEV1/RPCONT] [decimal](7, 0) NOT NULL,
	[/BEV1/RPSONST] [decimal](7, 0) NOT NULL,
	[/BEV1/RPFLGNR] [varchar](5) NOT NULL,
	[/SOPROMET/KZLEI] [varchar](1) NOT NULL,
	[BORGR_GRP] [varchar](35) NOT NULL
) ON [PRIMARY]
END
GO



IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[LIPS]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[LIPS](
	[MANDT] [varchar](3) NOT NULL,
	[VBELN] [varchar](10) NOT NULL,
	[POSNR] [varchar](6) NOT NULL,
	[PSTYV] [varchar](4) NOT NULL,
	[ERNAM] [varchar](12) NOT NULL,
	[ERZET] [varchar](6) NOT NULL,
	[ERDAT] [varchar](8) NOT NULL,
	[MATNR] [varchar](18) NOT NULL,
	[MATWA] [varchar](18) NOT NULL,
	[MATKL] [varchar](9) NOT NULL,
	[WERKS] [varchar](4) NOT NULL,
	[LGORT] [varchar](4) NOT NULL,
	[CHARG] [varchar](10) NOT NULL,
	[LICHN] [varchar](15) NOT NULL,
	[KDMAT] [varchar](35) NOT NULL,
	[PRODH] [varchar](18) NOT NULL,
	[LFIMG] [decimal](13, 3) NOT NULL,
	[MEINS] [varchar](3) NOT NULL,
	[VRKME] [varchar](3) NOT NULL,
	[UMVKZ] [decimal](5, 0) NOT NULL,
	[UMVKN] [decimal](5, 0) NOT NULL,
	[NTGEW] [decimal](15, 3) NOT NULL,
	[BRGEW] [decimal](15, 3) NOT NULL,
	[GEWEI] [varchar](3) NOT NULL,
	[VOLUM] [decimal](15, 3) NOT NULL,
	[VOLEH] [varchar](3) NOT NULL,
	[KZTLF] [varchar](1) NOT NULL,
	[UEBTK] [varchar](1) NOT NULL,
	[UEBTO] [decimal](3, 1) NOT NULL,
	[UNTTO] [decimal](3, 1) NOT NULL,
	[CHSPL] [varchar](1) NOT NULL,
	[FAKSP] [varchar](2) NOT NULL,
	[MBDAT] [varchar](8) NOT NULL,
	[LGMNG] [decimal](13, 3) NOT NULL,
	[ARKTX] [varchar](40) NOT NULL,
	[LGPBE] [varchar](10) NOT NULL,
	[VBELV] [varchar](10) NOT NULL,
	[POSNV] [varchar](6) NOT NULL,
	[VBTYV] [varchar](1) NOT NULL,
	[VGSYS] [varchar](10) NOT NULL,
	[VGBEL] [varchar](10) NOT NULL,
	[VGPOS] [varchar](6) NOT NULL,
	[UPFLU] [varchar](1) NOT NULL,
	[UEPOS] [varchar](6) NOT NULL,
	[FKREL] [varchar](1) NOT NULL,
	[LADGR] [varchar](4) NOT NULL,
	[TRAGR] [varchar](4) NOT NULL,
	[KOMKZ] [varchar](1) NOT NULL,
	[LGNUM] [varchar](3) NOT NULL,
	[LISPL] [varchar](1) NOT NULL,
	[LGTYP] [varchar](3) NOT NULL,
	[LGPLA] [varchar](10) NOT NULL,
	[BWTEX] [varchar](1) NOT NULL,
	[BWART] [varchar](3) NOT NULL,
	[BWLVS] [varchar](3) NOT NULL,
	[KZDLG] [varchar](1) NOT NULL,
	[BDART] [varchar](2) NOT NULL,
	[PLART] [varchar](1) NOT NULL,
	[MTART] [varchar](4) NOT NULL,
	[XCHPF] [varchar](1) NOT NULL,
	[XCHAR] [varchar](1) NOT NULL,
	[VGREF] [varchar](1) NOT NULL,
	[POSAR] [varchar](1) NOT NULL,
	[BWTAR] [varchar](10) NOT NULL,
	[SUMBD] [varchar](1) NOT NULL,
	[MTVFP] [varchar](2) NOT NULL,
	[EANNR] [varchar](13) NOT NULL,
	[GSBER] [varchar](4) NOT NULL,
	[VKBUR] [varchar](4) NOT NULL,
	[VKGRP] [varchar](3) NOT NULL,
	[VTWEG] [varchar](2) NOT NULL,
	[SPART] [varchar](2) NOT NULL,
	[GRKOR] [varchar](3) NOT NULL,
	[FMENG] [varchar](1) NOT NULL,
	[ANTLF] [decimal](1, 0) NOT NULL,
	[VBEAF] [decimal](5, 2) NOT NULL,
	[VBEAV] [decimal](5, 2) NOT NULL,
	[STAFO] [varchar](6) NOT NULL,
	[WAVWR] [decimal](13, 2) NOT NULL,
	[KZWI1] [decimal](13, 2) NOT NULL,
	[KZWI2] [decimal](13, 2) NOT NULL,
	[KZWI3] [decimal](13, 2) NOT NULL,
	[KZWI4] [decimal](13, 2) NOT NULL,
	[KZWI5] [decimal](13, 2) NOT NULL,
	[KZWI6] [decimal](13, 2) NOT NULL,
	[SOBKZ] [varchar](1) NOT NULL,
	[AEDAT] [varchar](8) NOT NULL,
	[EAN11] [varchar](18) NOT NULL,
	[KVGR1] [varchar](3) NOT NULL,
	[KVGR2] [varchar](3) NOT NULL,
	[KVGR3] [varchar](3) NOT NULL,
	[KVGR4] [varchar](3) NOT NULL,
	[KVGR5] [varchar](3) NOT NULL,
	[MVGR1] [varchar](3) NOT NULL,
	[MVGR2] [varchar](3) NOT NULL,
	[MVGR3] [varchar](3) NOT NULL,
	[MVGR4] [varchar](3) NOT NULL,
	[MVGR5] [varchar](3) NOT NULL,
	[VPZUO] [varchar](1) NOT NULL,
	[VGTYP] [varchar](1) NOT NULL,
	[RFVGTYP] [varchar](1) NOT NULL,
	[KOSTL] [varchar](10) NOT NULL,
	[KOKRS] [varchar](4) NOT NULL,
	[PAOBJNR] [varchar](10) NOT NULL,
	[PRCTR] [varchar](10) NOT NULL,
	[PS_PSP_PNR] [varchar](8) NOT NULL,
	[AUFNR] [varchar](12) NOT NULL,
	[POSNR_PP] [varchar](4) NOT NULL,
	[KDAUF] [varchar](10) NOT NULL,
	[KDPOS] [varchar](6) NOT NULL,
	[VPMAT] [varchar](18) NOT NULL,
	[VPWRK] [varchar](4) NOT NULL,
	[PRBME] [varchar](3) NOT NULL,
	[UMREF] [float] NOT NULL,
	[KNTTP] [varchar](1) NOT NULL,
	[KZVBR] [varchar](1) NOT NULL,
	[FIPOS] [varchar](14) NOT NULL,
	[FISTL] [varchar](16) NOT NULL,
	[GEBER] [varchar](10) NOT NULL,
	[PCKPF] [varchar](1) NOT NULL,
	[BEDAR_LF] [varchar](3) NOT NULL,
	[CMPNT] [varchar](1) NOT NULL,
	[KCMENG] [decimal](15, 3) NOT NULL,
	[KCBRGEW] [decimal](15, 3) NOT NULL,
	[KCNTGEW] [decimal](15, 3) NOT NULL,
	[KCVOLUM] [decimal](15, 3) NOT NULL,
	[UECHA] [varchar](6) NOT NULL,
	[CUOBJ] [varchar](18) NOT NULL,
	[CUOBJ_CH] [varchar](18) NOT NULL,
	[ANZSN] [int] NOT NULL,
	[SERAIL] [varchar](4) NOT NULL,
	[KCGEWEI] [varchar](3) NOT NULL,
	[KCVOLEH] [varchar](3) NOT NULL,
	[SERNR] [varchar](8) NOT NULL,
	[ABRLI] [varchar](4) NOT NULL,
	[ABART] [varchar](1) NOT NULL,
	[ABRVW] [varchar](3) NOT NULL,
	[QPLOS] [varchar](12) NOT NULL,
	[QTLOS] [varchar](6) NOT NULL,
	[NACHL] [varchar](1) NOT NULL,
	[MAGRV] [varchar](4) NOT NULL,
	[OBJKO] [varchar](22) NOT NULL,
	[OBJPO] [varchar](22) NOT NULL,
	[AESKD] [varchar](17) NOT NULL,
	[SHKZG] [varchar](1) NOT NULL,
	[PROSA] [varchar](1) NOT NULL,
	[UEPVW] [varchar](1) NOT NULL,
	[EMPST] [varchar](25) NOT NULL,
	[ABTNR] [varchar](4) NOT NULL,
	[KOQUI] [varchar](1) NOT NULL,
	[STADAT] [varchar](8) NOT NULL,
	[AKTNR] [varchar](10) NOT NULL,
	[KNUMH_CH] [varchar](10) NOT NULL,
	[PREFE] [varchar](1) NOT NULL,
	[EXART] [varchar](2) NOT NULL,
	[CLINT] [varchar](10) NOT NULL,
	[CHMVS] [varchar](3) NOT NULL,
	[ABELN] [varchar](10) NOT NULL,
	[ABELP] [varchar](5) NOT NULL,
	[LFIMG_FLO] [float] NOT NULL,
	[LGMNG_FLO] [float] NOT NULL,
	[KCMENG_FLO] [float] NOT NULL,
	[KZUMW] [varchar](1) NOT NULL,
	[KMPMG] [decimal](13, 3) NOT NULL,
	[AUREL] [varchar](1) NOT NULL,
	[KPEIN] [decimal](5, 0) NOT NULL,
	[KMEIN] [varchar](3) NOT NULL,
	[NETPR] [decimal](11, 2) NOT NULL,
	[NETWR] [decimal](15, 2) NOT NULL,
	[KOWRR] [varchar](1) NOT NULL,
	[KZBEW] [varchar](1) NOT NULL,
	[MFRGR] [varchar](8) NOT NULL,
	[CHHPV] [varchar](1) NOT NULL,
	[ABFOR] [varchar](2) NOT NULL,
	[ABGES] [float] NOT NULL,
	[MBUHR] [varchar](6) NOT NULL,
	[WKTNR] [varchar](10) NOT NULL,
	[WKTPS] [varchar](6) NOT NULL,
	[J_1BCFOP] [varchar](10) NOT NULL,
	[J_1BTAXLW1] [varchar](3) NOT NULL,
	[J_1BTAXLW2] [varchar](3) NOT NULL,
	[J_1BTXSDC] [varchar](2) NOT NULL,
	[SITUA] [varchar](2) NOT NULL,
	[RSNUM] [varchar](10) NOT NULL,
	[RSPOS] [varchar](4) NOT NULL,
	[RSART] [varchar](1) NOT NULL,
	[KANNR] [varchar](35) NOT NULL,
	[KZFME] [varchar](1) NOT NULL,
	[PROFL] [varchar](3) NOT NULL,
	[KCMENGVME] [decimal](15, 3) NOT NULL,
	[KCMENGVMEF] [float] NOT NULL,
	[KZBWS] [varchar](1) NOT NULL,
	[PSPNR] [varchar](8) NOT NULL,
	[EPRIO] [varchar](4) NOT NULL,
	[RULES] [varchar](4) NOT NULL,
	[KZBEF] [varchar](1) NOT NULL,
	[MPROF] [varchar](4) NOT NULL,
	[EMATN] [varchar](18) NOT NULL,
	[LGBZO] [varchar](10) NOT NULL,
	[HANDLE] [varchar](22) NOT NULL,
	[VERURPOS] [varchar](6) NOT NULL,
	[LIFEXPOS] [varchar](6) NOT NULL,
	[NOATP] [varchar](1) NOT NULL,
	[NOPCK] [varchar](1) NOT NULL,
	[RBLVS] [varchar](3) NOT NULL,
	[BERID] [varchar](10) NOT NULL,
	[BESTQ] [varchar](1) NOT NULL,
	[UMBSQ] [varchar](1) NOT NULL,
	[UMMAT] [varchar](18) NOT NULL,
	[UMWRK] [varchar](4) NOT NULL,
	[UMLGO] [varchar](4) NOT NULL,
	[UMCHA] [varchar](10) NOT NULL,
	[UMBAR] [varchar](10) NOT NULL,
	[UMSOK] [varchar](1) NOT NULL,
	[SONUM] [varchar](16) NOT NULL,
	[USONU] [varchar](16) NOT NULL,
	[AKKUR] [decimal](9, 5) NOT NULL,
	[AKMNG] [varchar](1) NOT NULL,
	[VKGRU] [varchar](3) NOT NULL,
	[SHKZG_UM] [varchar](1) NOT NULL,
	[INSMK] [varchar](1) NOT NULL,
	[KZECH] [varchar](1) NOT NULL,
	[FLGWM] [varchar](1) NOT NULL,
	[BERKZ] [varchar](1) NOT NULL,
	[HUPOS] [varchar](1) NOT NULL,
	[NOWAB] [varchar](1) NOT NULL,
	[KONTO] [varchar](10) NOT NULL,
	[KZEAR] [varchar](1) NOT NULL,
	[HSDAT] [varchar](8) NOT NULL,
	[VFDAT] [varchar](8) NOT NULL,
	[LFGJA] [varchar](4) NOT NULL,
	[LFBNR] [varchar](10) NOT NULL,
	[LFPOS] [varchar](4) NOT NULL,
	[GRUND] [varchar](4) NOT NULL,
	[FOBWA] [varchar](3) NOT NULL,
	[DLVTP] [varchar](2) NOT NULL,
	[EXBWR] [decimal](13, 2) NOT NULL,
	[BPMNG] [decimal](13, 3) NOT NULL,
	[EXVKW] [decimal](13, 2) NOT NULL,
	[CMPRE_FLT] [float] NOT NULL,
	[KZPOD] [varchar](1) NOT NULL,
	[LFDEZ] [varchar](1) NOT NULL,
	[UMREV] [float] NOT NULL,
	[PODREL] [varchar](1) NOT NULL,
	[KZUML] [varchar](1) NOT NULL,
	[FKBER] [varchar](16) NOT NULL,
	[GRANT_NBR] [varchar](20) NOT NULL,
	[KZWSO] [varchar](1) NOT NULL,
	[GMCONTROL] [varchar](1) NOT NULL,
	[POSTING_CHANGE] [varchar](1) NOT NULL,
	[UM_PS_PSP_PNR] [varchar](8) NOT NULL,
	[PRE_VL_ETENS] [varchar](4) NOT NULL,
	[SPE_GEN_ELIKZ] [varchar](1) NOT NULL,
	[SPE_SCRAP_IND] [varchar](1) NOT NULL,
	[SPE_AUTH_NUMBER] [varchar](20) NOT NULL,
	[SPE_INSPOUT_GUID] [varbinary](16) NULL,
	[SPE_FOLLOW_UP] [varchar](4) NOT NULL,
	[SPE_EXP_DATE_EXT] [decimal](15, 0) NOT NULL,
	[SPE_EXP_DATE_INT] [decimal](15, 0) NOT NULL,
	[SPE_AUTH_COMPLET] [varchar](1) NOT NULL,
	[ORMNG] [decimal](13, 3) NOT NULL,
	[SPE_ATP_TMSTMP] [decimal](15, 0) NOT NULL,
	[SPE_ORIG_SYS] [varchar](1) NOT NULL,
	[SPE_LIEFFZ] [decimal](15, 3) NOT NULL,
	[SPE_IMWRK] [varchar](1) NOT NULL,
	[SPE_LIFEXPOS2] [varchar](35) NOT NULL,
	[SPE_EXCEPT_CODE] [varchar](4) NOT NULL,
	[SPE_KEEP_QTY] [decimal](13, 3) NOT NULL,
	[SPE_ALTERNATE] [varchar](40) NOT NULL,
	[SPE_MAT_SUBST] [varchar](1) NOT NULL,
	[SPE_STRUC] [varchar](3) NOT NULL,
	[SPE_APO_QNTYFAC] [decimal](5, 0) NOT NULL,
	[SPE_APO_QNTYDIV] [decimal](5, 0) NOT NULL,
	[SPE_HERKL] [varchar](3) NOT NULL,
	[SPE_BXP_DATE_EXT] [decimal](15, 0) NOT NULL,
	[SPE_COMPL_MVT] [varchar](1) NOT NULL,
	[J_1BTAXLW4] [varchar](3) NOT NULL,
	[J_1BTAXLW5] [varchar](3) NOT NULL,
	[J_1BTAXLW3] [varchar](3) NOT NULL,
	[/SOPROMET/KOSTL] [varchar](10) NOT NULL,
	[/SOPROMET/NOSHP] [varchar](1) NOT NULL,
	[CONS_ORDER] [varchar](1) NOT NULL,
	[ZZBOMSTATUS] [varchar](1) NULL
) ON [PRIMARY]
END
GO



IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[MAKT]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[MAKT](
	[MANDT] [varchar](3) NOT NULL,
	[MATNR] [varchar](18) NOT NULL,
	[SPRAS] [varchar](1) NOT NULL,
	[MAKTX] [varchar](40) NOT NULL,
	[MAKTG] [varchar](40) NOT NULL
) ON [PRIMARY]
END
GO



IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[MARA]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[MARA](
	[MANDT] [varchar](3) NOT NULL,
	[MATNR] [varchar](18) NOT NULL,
	[ERSDA] [varchar](8) NOT NULL,
	[ERNAM] [varchar](12) NOT NULL,
	[LAEDA] [varchar](8) NOT NULL,
	[AENAM] [varchar](12) NOT NULL,
	[VPSTA] [varchar](15) NOT NULL,
	[PSTAT] [varchar](15) NOT NULL,
	[LVORM] [varchar](1) NOT NULL,
	[MTART] [varchar](4) NOT NULL,
	[MBRSH] [varchar](1) NOT NULL,
	[MATKL] [varchar](9) NOT NULL,
	[BISMT] [varchar](18) NOT NULL,
	[MEINS] [varchar](3) NOT NULL,
	[BSTME] [varchar](3) NOT NULL,
	[ZEINR] [varchar](22) NOT NULL,
	[ZEIAR] [varchar](3) NOT NULL,
	[ZEIVR] [varchar](2) NOT NULL,
	[ZEIFO] [varchar](4) NOT NULL,
	[AESZN] [varchar](6) NOT NULL,
	[BLATT] [varchar](3) NOT NULL,
	[BLANZ] [varchar](3) NOT NULL,
	[FERTH] [varchar](18) NOT NULL,
	[FORMT] [varchar](4) NOT NULL,
	[GROES] [varchar](32) NOT NULL,
	[WRKST] [varchar](48) NOT NULL,
	[NORMT] [varchar](18) NOT NULL,
	[LABOR] [varchar](3) NOT NULL,
	[EKWSL] [varchar](4) NOT NULL,
	[BRGEW] [decimal](13, 3) NOT NULL,
	[NTGEW] [decimal](13, 3) NOT NULL,
	[GEWEI] [varchar](3) NOT NULL,
	[VOLUM] [decimal](13, 3) NOT NULL,
	[VOLEH] [varchar](3) NOT NULL,
	[BEHVO] [varchar](2) NOT NULL,
	[RAUBE] [varchar](2) NOT NULL,
	[TEMPB] [varchar](2) NOT NULL,
	[DISST] [varchar](3) NOT NULL,
	[TRAGR] [varchar](4) NOT NULL,
	[STOFF] [varchar](18) NOT NULL,
	[SPART] [varchar](2) NOT NULL,
	[KUNNR] [varchar](10) NOT NULL,
	[EANNR] [varchar](13) NOT NULL,
	[WESCH] [decimal](13, 3) NOT NULL,
	[BWVOR] [varchar](1) NOT NULL,
	[BWSCL] [varchar](1) NOT NULL,
	[SAISO] [varchar](4) NOT NULL,
	[ETIAR] [varchar](2) NOT NULL,
	[ETIFO] [varchar](2) NOT NULL,
	[ENTAR] [varchar](1) NOT NULL,
	[EAN11] [varchar](18) NOT NULL,
	[NUMTP] [varchar](2) NOT NULL,
	[LAENG] [decimal](13, 3) NOT NULL,
	[BREIT] [decimal](13, 3) NOT NULL,
	[HOEHE] [decimal](13, 3) NOT NULL,
	[MEABM] [varchar](3) NOT NULL,
	[PRDHA] [varchar](18) NOT NULL,
	[AEKLK] [varchar](1) NOT NULL,
	[CADKZ] [varchar](1) NOT NULL,
	[QMPUR] [varchar](1) NOT NULL,
	[ERGEW] [decimal](13, 3) NOT NULL,
	[ERGEI] [varchar](3) NOT NULL,
	[ERVOL] [decimal](13, 3) NOT NULL,
	[ERVOE] [varchar](3) NOT NULL,
	[GEWTO] [decimal](3, 1) NOT NULL,
	[VOLTO] [decimal](3, 1) NOT NULL,
	[VABME] [varchar](1) NOT NULL,
	[KZREV] [varchar](1) NOT NULL,
	[KZKFG] [varchar](1) NOT NULL,
	[XCHPF] [varchar](1) NOT NULL,
	[VHART] [varchar](4) NOT NULL,
	[FUELG] [decimal](3, 0) NOT NULL,
	[STFAK] [smallint] NOT NULL,
	[MAGRV] [varchar](4) NOT NULL,
	[BEGRU] [varchar](4) NOT NULL,
	[DATAB] [varchar](8) NOT NULL,
	[LIQDT] [varchar](8) NOT NULL,
	[SAISJ] [varchar](4) NOT NULL,
	[PLGTP] [varchar](2) NOT NULL,
	[MLGUT] [varchar](1) NOT NULL,
	[EXTWG] [varchar](18) NOT NULL,
	[SATNR] [varchar](18) NOT NULL,
	[ATTYP] [varchar](2) NOT NULL,
	[KZKUP] [varchar](1) NOT NULL,
	[KZNFM] [varchar](1) NOT NULL,
	[PMATA] [varchar](18) NOT NULL,
	[MSTAE] [varchar](2) NOT NULL,
	[MSTAV] [varchar](2) NOT NULL,
	[MSTDE] [varchar](8) NOT NULL,
	[MSTDV] [varchar](8) NOT NULL,
	[TAKLV] [varchar](1) NOT NULL,
	[RBNRM] [varchar](9) NOT NULL,
	[MHDRZ] [decimal](4, 0) NOT NULL,
	[MHDHB] [decimal](4, 0) NOT NULL,
	[MHDLP] [decimal](3, 0) NOT NULL,
	[INHME] [varchar](3) NOT NULL,
	[INHAL] [decimal](13, 3) NOT NULL,
	[VPREH] [decimal](5, 0) NOT NULL,
	[ETIAG] [varchar](18) NOT NULL,
	[INHBR] [decimal](13, 3) NOT NULL,
	[CMETH] [varchar](1) NOT NULL,
	[CUOBF] [varchar](18) NOT NULL,
	[KZUMW] [varchar](1) NOT NULL,
	[KOSCH] [varchar](18) NOT NULL,
	[SPROF] [varchar](1) NOT NULL,
	[NRFHG] [varchar](1) NOT NULL,
	[MFRPN] [varchar](40) NOT NULL,
	[MFRNR] [varchar](10) NOT NULL,
	[BMATN] [varchar](18) NOT NULL,
	[MPROF] [varchar](4) NOT NULL,
	[KZWSM] [varchar](1) NOT NULL,
	[SAITY] [varchar](2) NOT NULL,
	[PROFL] [varchar](3) NOT NULL,
	[IHIVI] [varchar](1) NOT NULL,
	[ILOOS] [varchar](1) NOT NULL,
	[SERLV] [varchar](1) NOT NULL,
	[KZGVH] [varchar](1) NOT NULL,
	[XGCHP] [varchar](1) NOT NULL,
	[KZEFF] [varchar](1) NOT NULL,
	[COMPL] [varchar](2) NOT NULL,
	[IPRKZ] [varchar](1) NOT NULL,
	[RDMHD] [varchar](1) NOT NULL,
	[PRZUS] [varchar](1) NOT NULL,
	[MTPOS_MARA] [varchar](4) NOT NULL,
	[BFLME] [varchar](1) NOT NULL,
	[MATFI] [varchar](1) NOT NULL,
	[CMREL] [varchar](1) NOT NULL,
	[BBTYP] [varchar](1) NOT NULL,
	[SLED_BBD] [varchar](1) NOT NULL,
	[GTIN_VARIANT] [varchar](2) NOT NULL,
	[GENNR] [varchar](18) NOT NULL,
	[RMATP] [varchar](18) NOT NULL,
	[GDS_RELEVANT] [varchar](1) NOT NULL,
	[WEORA] [varchar](1) NOT NULL,
	[HUTYP_DFLT] [varchar](4) NOT NULL,
	[PILFERABLE] [varchar](1) NOT NULL,
	[WHSTC] [varchar](2) NOT NULL,
	[WHMATGR] [varchar](4) NOT NULL,
	[HNDLCODE] [varchar](4) NOT NULL,
	[HAZMAT] [varchar](1) NOT NULL,
	[HUTYP] [varchar](4) NOT NULL,
	[TARE_VAR] [varchar](1) NOT NULL,
	[MAXC] [decimal](15, 3) NOT NULL,
	[MAXC_TOL] [decimal](3, 1) NOT NULL,
	[MAXL] [decimal](15, 3) NOT NULL,
	[MAXB] [decimal](15, 3) NOT NULL,
	[MAXH] [decimal](15, 3) NOT NULL,
	[MAXDIM_UOM] [varchar](3) NOT NULL,
	[HERKL] [varchar](3) NOT NULL,
	[MFRGR] [varchar](8) NOT NULL,
	[QQTIME] [decimal](3, 0) NOT NULL,
	[QQTIMEUOM] [varchar](3) NOT NULL,
	[QGRP] [varchar](4) NOT NULL,
	[SERIAL] [varchar](4) NOT NULL,
	[PS_SMARTFORM] [varchar](30) NOT NULL,
	[LOGUNIT] [varchar](3) NOT NULL,
	[CWQREL] [varchar](1) NOT NULL,
	[CWQPROC] [varchar](2) NOT NULL,
	[CWQTOLGR] [varchar](9) NOT NULL,
	[/BEV1/LULEINH] [varchar](8) NOT NULL,
	[/BEV1/LULDEGRP] [varchar](3) NOT NULL,
	[/BEV1/NESTRUCCAT] [varchar](1) NOT NULL,
	[/DSD/VC_GROUP] [varchar](6) NOT NULL,
	[/VSO/R_TILT_IND] [varchar](1) NOT NULL,
	[/VSO/R_STACK_IND] [varchar](1) NOT NULL,
	[/VSO/R_BOT_IND] [varchar](1) NOT NULL,
	[/VSO/R_TOP_IND] [varchar](1) NOT NULL,
	[/VSO/R_STACK_NO] [varchar](3) NOT NULL,
	[/VSO/R_PAL_IND] [varchar](1) NOT NULL,
	[/VSO/R_PAL_OVR_D] [decimal](13, 3) NOT NULL,
	[/VSO/R_PAL_OVR_W] [decimal](13, 3) NOT NULL,
	[/VSO/R_PAL_B_HT] [decimal](13, 3) NOT NULL,
	[/VSO/R_PAL_MIN_H] [decimal](13, 3) NOT NULL,
	[/VSO/R_TOL_B_HT] [decimal](13, 3) NOT NULL,
	[/VSO/R_NO_P_GVH] [varchar](2) NOT NULL,
	[/VSO/R_QUAN_UNIT] [varchar](3) NOT NULL,
	[/VSO/R_KZGVH_IND] [varchar](1) NOT NULL,
	[MCOND] [varchar](1) NOT NULL,
	[RETDELC] [varchar](1) NOT NULL,
	[LOGLEV_RETO] [varchar](1) NOT NULL,
	[NSNID] [varchar](9) NOT NULL,
	[IMATN] [varchar](18) NOT NULL,
	[PICNUM] [varchar](18) NOT NULL,
	[BSTAT] [varchar](2) NOT NULL,
	[COLOR_ATINN] [varchar](10) NOT NULL,
	[SIZE1_ATINN] [varchar](10) NOT NULL,
	[SIZE2_ATINN] [varchar](10) NOT NULL,
	[COLOR] [varchar](18) NOT NULL,
	[SIZE1] [varchar](18) NOT NULL,
	[SIZE2] [varchar](18) NOT NULL,
	[FREE_CHAR] [varchar](18) NOT NULL,
	[CARE_CODE] [varchar](16) NOT NULL,
	[BRAND_ID] [varchar](4) NOT NULL,
	[FIBER_CODE1] [varchar](3) NOT NULL,
	[FIBER_PART1] [varchar](3) NOT NULL,
	[FIBER_CODE2] [varchar](3) NOT NULL,
	[FIBER_PART2] [varchar](3) NOT NULL,
	[FIBER_CODE3] [varchar](3) NOT NULL,
	[FIBER_PART3] [varchar](3) NOT NULL,
	[FIBER_CODE4] [varchar](3) NOT NULL,
	[FIBER_PART4] [varchar](3) NOT NULL,
	[FIBER_CODE5] [varchar](3) NOT NULL,
	[FIBER_PART5] [varchar](3) NOT NULL,
	[FASHGRD] [varchar](4) NOT NULL,
	[ZPRODUCT_MANAGER] [varchar](40) NULL,
	[ZENGINEER] [varchar](40) NULL,
	[ZREORDERCODE] [varchar](18) NULL,
	[ZFORECASTREL] [varchar](1) NULL,
	[ZUSREGULATORY] [varchar](7) NULL,
	[ZTECHNICALFILE] [varchar](8) NULL,
	[ZDESIGNHISTORY] [varchar](8) NULL,
	[ZVMI] [varchar](1) NULL,
	[ZSETPURPOSE] [varchar](40) NULL,
	[ZSETSTATUS] [varchar](10) NULL,
	[ZSETREPLACEDBY] [varchar](40) NULL,
	[ZSETCONTRIBUTION] [varchar](10) NULL,
	[ZSURGERYASP] [decimal](13, 2) NULL,
	[ZSURGERYLVL] [decimal](5, 2) NULL,
	[ZEKGRP] [varchar](3) NULL,
	[ZDISPO] [varchar](3) NULL,
	[ZCUSTMAT] [varchar](1) NULL,
	[ZVEND] [varchar](1) NULL,
	[ZNUVAVEND] [varchar](1) NULL,
	[ZPURPOSE] [varchar](10) NULL,
	[ZCOUNTRYSPEC] [varchar](10) NULL
) ON [PRIMARY]
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[STPO]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[STPO](
	[MANDT] [varchar](3) NOT NULL,
	[STLTY] [varchar](1) NOT NULL,
	[STLNR] [varchar](8) NOT NULL,
	[STLKN] [varchar](8) NOT NULL,
	[STPOZ] [varchar](8) NOT NULL,
	[DATUV] [varchar](8) NOT NULL,
	[TECHV] [varchar](12) NOT NULL,
	[AENNR] [varchar](12) NOT NULL,
	[LKENZ] [varchar](1) NOT NULL,
	[VGKNT] [varchar](8) NOT NULL,
	[VGPZL] [varchar](8) NOT NULL,
	[ANDAT] [varchar](8) NOT NULL,
	[ANNAM] [varchar](12) NOT NULL,
	[AEDAT] [varchar](8) NOT NULL,
	[AENAM] [varchar](12) NOT NULL,
	[IDNRK] [varchar](18) NOT NULL,
	[PSWRK] [varchar](4) NOT NULL,
	[POSTP] [varchar](1) NOT NULL,
	[POSNR] [varchar](4) NOT NULL,
	[SORTF] [varchar](10) NOT NULL,
	[MEINS] [varchar](3) NOT NULL,
	[MENGE] [decimal](13, 3) NOT NULL,
	[FMENG] [varchar](1) NOT NULL,
	[AUSCH] [decimal](5, 2) NOT NULL,
	[AVOAU] [decimal](5, 2) NOT NULL,
	[NETAU] [varchar](1) NOT NULL,
	[SCHGT] [varchar](1) NOT NULL,
	[BEIKZ] [varchar](1) NOT NULL,
	[ERSKZ] [varchar](1) NOT NULL,
	[RVREL] [varchar](1) NOT NULL,
	[SANFE] [varchar](1) NOT NULL,
	[SANIN] [varchar](1) NOT NULL,
	[SANKA] [varchar](1) NOT NULL,
	[SANKO] [varchar](1) NOT NULL,
	[SANVS] [varchar](1) NOT NULL,
	[STKKZ] [varchar](1) NOT NULL,
	[REKRI] [varchar](1) NOT NULL,
	[REKRS] [varchar](1) NOT NULL,
	[CADPO] [varchar](1) NOT NULL,
	[NFMAT] [varchar](18) NOT NULL,
	[NLFZT] [decimal](3, 0) NOT NULL,
	[VERTI] [varchar](4) NOT NULL,
	[ALPOS] [varchar](1) NOT NULL,
	[EWAHR] [decimal](3, 0) NOT NULL,
	[EKGRP] [varchar](3) NOT NULL,
	[LIFZT] [decimal](3, 0) NOT NULL,
	[LIFNR] [varchar](10) NOT NULL,
	[PREIS] [decimal](11, 2) NOT NULL,
	[PEINH] [decimal](5, 0) NOT NULL,
	[WAERS] [varchar](5) NOT NULL,
	[SAKTO] [varchar](10) NOT NULL,
	[ROANZ] [decimal](13, 3) NOT NULL,
	[ROMS1] [decimal](13, 3) NOT NULL,
	[ROMS2] [decimal](13, 3) NOT NULL,
	[ROMS3] [decimal](13, 3) NOT NULL,
	[ROMEI] [varchar](3) NOT NULL,
	[ROMEN] [decimal](13, 3) NOT NULL,
	[RFORM] [varchar](2) NOT NULL,
	[UPSKZ] [varchar](1) NOT NULL,
	[VALKZ] [varchar](1) NOT NULL,
	[LTXSP] [varchar](1) NOT NULL,
	[POTX1] [varchar](40) NOT NULL,
	[POTX2] [varchar](40) NOT NULL,
	[OBJTY] [varchar](1) NOT NULL,
	[MATKL] [varchar](9) NOT NULL,
	[WEBAZ] [decimal](3, 0) NOT NULL,
	[DOKAR] [varchar](3) NOT NULL,
	[DOKNR] [varchar](25) NOT NULL,
	[DOKVR] [varchar](2) NOT NULL,
	[DOKTL] [varchar](3) NOT NULL,
	[CSSTR] [decimal](5, 2) NOT NULL,
	[CLASS] [varchar](18) NOT NULL,
	[KLART] [varchar](3) NOT NULL,
	[POTPR] [varchar](1) NOT NULL,
	[AWAKZ] [varchar](1) NOT NULL,
	[INSKZ] [varchar](1) NOT NULL,
	[VCEKZ] [varchar](1) NOT NULL,
	[VSTKZ] [varchar](1) NOT NULL,
	[VACKZ] [varchar](1) NOT NULL,
	[EKORG] [varchar](4) NOT NULL,
	[CLOBK] [varchar](1) NOT NULL,
	[CLMUL] [varchar](1) NOT NULL,
	[CLALT] [varchar](1) NOT NULL,
	[CVIEW] [varchar](10) NOT NULL,
	[KNOBJ] [varchar](18) NOT NULL,
	[LGORT] [varchar](4) NOT NULL,
	[KZKUP] [varchar](1) NOT NULL,
	[INTRM] [varchar](18) NOT NULL,
	[TPEKZ] [varchar](1) NOT NULL,
	[STVKN] [varchar](8) NOT NULL,
	[DVDAT] [varchar](8) NOT NULL,
	[DVNAM] [varchar](12) NOT NULL,
	[DSPST] [varchar](2) NOT NULL,
	[ALPST] [varchar](1) NOT NULL,
	[ALPRF] [varchar](2) NOT NULL,
	[ALPGR] [varchar](2) NOT NULL,
	[KZNFP] [varchar](1) NOT NULL,
	[NFGRP] [varchar](2) NOT NULL,
	[NFEAG] [varchar](2) NOT NULL,
	[KNDVB] [varchar](1) NOT NULL,
	[KNDBZ] [varchar](1) NOT NULL,
	[KSTTY] [varchar](1) NOT NULL,
	[KSTNR] [varchar](8) NOT NULL,
	[KSTKN] [varchar](8) NOT NULL,
	[KSTPZ] [varchar](8) NOT NULL,
	[CLSZU] [varchar](8) NOT NULL,
	[KZCLB] [varchar](1) NOT NULL,
	[AEHLP] [varchar](2) NOT NULL,
	[PRVBE] [varchar](10) NOT NULL,
	[NLFZV] [decimal](3, 0) NOT NULL,
	[NLFMV] [varchar](3) NOT NULL,
	[IDPOS] [varchar](20) NOT NULL,
	[IDHIS] [varchar](5) NOT NULL,
	[IDVAR] [varchar](5) NOT NULL,
	[ALEKZ] [varchar](1) NOT NULL,
	[ITMID] [varchar](8) NOT NULL,
	[GUID] [varchar](22) NOT NULL,
	[ITSOB] [varchar](2) NOT NULL,
	[RFPNT] [varchar](20) NOT NULL,
	[GUIDX] [varbinary](16) NULL,
	[/SOPROMET/SERNR] [varchar](18) NOT NULL
) ON [PRIMARY]
END
GO



IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[T179T]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[T179T](
	[MANDT] [varchar](3) NOT NULL,
	[SPRAS] [varchar](1) NOT NULL,
	[PRODH] [varchar](18) NOT NULL,
	[VTEXT] [varchar](40) NOT NULL
) ON [PRIMARY]
END
GO



IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[TVM4T]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[TVM4T](
	[MANDT] [varchar](3) NOT NULL,
	[SPRAS] [varchar](1) NOT NULL,
	[MVGR4] [varchar](3) NOT NULL,
	[BEZEI] [varchar](40) NOT NULL
) ON [PRIMARY]
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[VBAK]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[VBAK](
	[MANDT] [varchar](3) NOT NULL,
	[VBELN] [varchar](10) NOT NULL,
	[ERDAT] [varchar](8) NOT NULL,
	[ERZET] [varchar](6) NOT NULL,
	[ERNAM] [varchar](12) NOT NULL,
	[ANGDT] [varchar](8) NOT NULL,
	[BNDDT] [varchar](8) NOT NULL,
	[AUDAT] [varchar](8) NOT NULL,
	[VBTYP] [varchar](1) NOT NULL,
	[TRVOG] [varchar](1) NOT NULL,
	[AUART] [varchar](4) NOT NULL,
	[AUGRU] [varchar](3) NOT NULL,
	[GWLDT] [varchar](8) NOT NULL,
	[SUBMI] [varchar](10) NOT NULL,
	[LIFSK] [varchar](2) NOT NULL,
	[FAKSK] [varchar](2) NOT NULL,
	[NETWR] [decimal](15, 2) NOT NULL,
	[WAERK] [varchar](5) NOT NULL,
	[VKORG] [varchar](4) NOT NULL,
	[VTWEG] [varchar](2) NOT NULL,
	[SPART] [varchar](2) NOT NULL,
	[VKGRP] [varchar](3) NOT NULL,
	[VKBUR] [varchar](4) NOT NULL,
	[GSBER] [varchar](4) NOT NULL,
	[GSKST] [varchar](4) NOT NULL,
	[GUEBG] [varchar](8) NOT NULL,
	[GUEEN] [varchar](8) NOT NULL,
	[KNUMV] [varchar](10) NOT NULL,
	[VDATU] [varchar](8) NOT NULL,
	[VPRGR] [varchar](1) NOT NULL,
	[AUTLF] [varchar](1) NOT NULL,
	[VBKLA] [varchar](9) NOT NULL,
	[VBKLT] [varchar](1) NOT NULL,
	[KALSM] [varchar](6) NOT NULL,
	[VSBED] [varchar](2) NOT NULL,
	[FKARA] [varchar](4) NOT NULL,
	[AWAHR] [varchar](3) NOT NULL,
	[KTEXT] [varchar](40) NOT NULL,
	[BSTNK] [varchar](20) NOT NULL,
	[BSARK] [varchar](4) NOT NULL,
	[BSTDK] [varchar](8) NOT NULL,
	[BSTZD] [varchar](4) NOT NULL,
	[IHREZ] [varchar](12) NOT NULL,
	[BNAME] [varchar](35) NOT NULL,
	[TELF1] [varchar](16) NOT NULL,
	[MAHZA] [decimal](3, 0) NOT NULL,
	[MAHDT] [varchar](8) NOT NULL,
	[KUNNR] [varchar](10) NOT NULL,
	[KOSTL] [varchar](10) NOT NULL,
	[STAFO] [varchar](6) NOT NULL,
	[STWAE] [varchar](5) NOT NULL,
	[AEDAT] [varchar](8) NOT NULL,
	[KVGR1] [varchar](3) NOT NULL,
	[KVGR2] [varchar](3) NOT NULL,
	[KVGR3] [varchar](3) NOT NULL,
	[KVGR4] [varchar](3) NOT NULL,
	[KVGR5] [varchar](3) NOT NULL,
	[KNUMA] [varchar](10) NOT NULL,
	[KOKRS] [varchar](4) NOT NULL,
	[PS_PSP_PNR] [varchar](8) NOT NULL,
	[KURST] [varchar](4) NOT NULL,
	[KKBER] [varchar](4) NOT NULL,
	[KNKLI] [varchar](10) NOT NULL,
	[GRUPP] [varchar](4) NOT NULL,
	[SBGRP] [varchar](3) NOT NULL,
	[CTLPC] [varchar](3) NOT NULL,
	[CMWAE] [varchar](5) NOT NULL,
	[CMFRE] [varchar](8) NOT NULL,
	[CMNUP] [varchar](8) NOT NULL,
	[CMNGV] [varchar](8) NOT NULL,
	[AMTBL] [decimal](15, 2) NOT NULL,
	[HITYP_PR] [varchar](1) NOT NULL,
	[ABRVW] [varchar](3) NOT NULL,
	[ABDIS] [varchar](1) NOT NULL,
	[VGBEL] [varchar](10) NOT NULL,
	[OBJNR] [varchar](22) NOT NULL,
	[BUKRS_VF] [varchar](4) NOT NULL,
	[TAXK1] [varchar](1) NOT NULL,
	[TAXK2] [varchar](1) NOT NULL,
	[TAXK3] [varchar](1) NOT NULL,
	[TAXK4] [varchar](1) NOT NULL,
	[TAXK5] [varchar](1) NOT NULL,
	[TAXK6] [varchar](1) NOT NULL,
	[TAXK7] [varchar](1) NOT NULL,
	[TAXK8] [varchar](1) NOT NULL,
	[TAXK9] [varchar](1) NOT NULL,
	[XBLNR] [varchar](16) NOT NULL,
	[ZUONR] [varchar](18) NOT NULL,
	[VGTYP] [varchar](1) NOT NULL,
	[KALSM_CH] [varchar](6) NOT NULL,
	[AGRZR] [varchar](2) NOT NULL,
	[AUFNR] [varchar](12) NOT NULL,
	[QMNUM] [varchar](12) NOT NULL,
	[VBELN_GRP] [varchar](10) NOT NULL,
	[SCHEME_GRP] [varchar](4) NOT NULL,
	[ABRUF_PART] [varchar](1) NOT NULL,
	[ABHOD] [varchar](8) NOT NULL,
	[ABHOV] [varchar](6) NOT NULL,
	[ABHOB] [varchar](6) NOT NULL,
	[RPLNR] [varchar](10) NOT NULL,
	[VZEIT] [varchar](6) NOT NULL,
	[STCEG_L] [varchar](3) NOT NULL,
	[LANDTX] [varchar](3) NOT NULL,
	[XEGDR] [varchar](1) NOT NULL,
	[ENQUEUE_GRP] [varchar](1) NOT NULL,
	[DAT_FZAU] [varchar](8) NOT NULL,
	[FMBDAT] [varchar](8) NOT NULL,
	[VSNMR_V] [varchar](12) NOT NULL,
	[HANDLE] [varchar](22) NOT NULL,
	[PROLI] [varchar](3) NOT NULL,
	[CONT_DG] [varchar](1) NOT NULL,
	[CRM_GUID] [varchar](70) NOT NULL,
	[/SOPROMET/LRESN] [varchar](10) NOT NULL,
	[/SOPROMET/EQUNR] [varchar](18) NOT NULL,
	[/SOPROMET/KZLEI] [varchar](1) NOT NULL,
	[/SOPROMET/NBOMU] [varchar](1) NOT NULL,
	[SWENR] [varchar](8) NOT NULL,
	[SMENR] [varchar](8) NOT NULL,
	[PHASE] [varchar](11) NOT NULL,
	[MTLAUR] [varchar](1) NOT NULL,
	[STAGE] [int] NOT NULL,
	[HB_CONT_REASON] [varchar](2) NOT NULL,
	[HB_EXPDATE] [varchar](8) NOT NULL,
	[HB_RESDATE] [varchar](8) NOT NULL,
	[LOGSYSB] [varchar](10) NOT NULL,
	[KALCD] [varchar](6) NOT NULL,
	[MULTI] [varchar](1) NOT NULL,
	[ZZDEA_NUM] [varchar](10) NOT NULL,
	[ZZFORM_222] [varchar](9) NOT NULL,
	[ZZEXPIRY] [varchar](8) NOT NULL,
	[ZZ_SURGERY] [varchar](20) NOT NULL,
	[ZZ_AIRBILL] [varchar](40) NOT NULL,
	[ZZ_SCHED] [varchar](30) NOT NULL,
	[ZZTRACKNUM] [varchar](150) NOT NULL,
	[ZZ_SURGERY_NO] [varchar](20) NOT NULL,
	[ZZ_SURGERY_DATE] [varchar](8) NOT NULL,
	[ZZ_SURGERY_PR] [varchar](20) NOT NULL,
	[ZZODATE] [varchar](8) NULL,
	[ZZRDATE] [varchar](8) NULL,
	[ZZVDATE] [varchar](8) NULL,
	[ZZABDAT] [varchar](8) NULL,
	[ZZRSTYP] [varchar](2) NULL,
	[ZZFRDAT] [varchar](8) NULL,
	[ZZSFNAM] [varchar](35) NULL,
	[ZZSLNAM] [varchar](35) NULL,
	[ZZ_EXCRPT] [varchar](1) NULL,
	[ZZ_EXCLLRPT] [varchar](1) NULL,
	[ZZTELF1] [varchar](50) NULL,
 CONSTRAINT [PK_VBAK] PRIMARY KEY NONCLUSTERED 
(
	[MANDT] ASC,
	[VBELN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
END
GO



IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[VBAP]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[VBAP](
	[MANDT] [varchar](3) NULL,
	[VBELN] [varchar](10) NULL,
	[POSNR] [varchar](6) NULL,
	[MATNR] [varchar](18) NULL,
	[MATWA] [varchar](18) NULL,
	[PMATN] [varchar](18) NULL,
	[CHARG] [varchar](10) NULL,
	[MATKL] [varchar](9) NULL,
	[ARKTX] [varchar](40) NULL,
	[PSTYV] [varchar](4) NULL,
	[POSAR] [varchar](1) NULL,
	[LFREL] [varchar](1) NULL,
	[FKREL] [varchar](1) NULL,
	[UEPOS] [varchar](6) NULL,
	[GRPOS] [varchar](6) NULL,
	[ABGRU] [varchar](2) NULL,
	[PRODH] [varchar](18) NULL,
	[ZWERT] [numeric](13, 2) NULL,
	[ZMENG] [numeric](13, 3) NULL,
	[ZIEME] [varchar](3) NULL,
	[UMZIZ] [numeric](5, 0) NULL,
	[UMZIN] [numeric](5, 0) NULL,
	[MEINS] [varchar](3) NULL,
	[SMENG] [numeric](13, 3) NULL,
	[ABLFZ] [numeric](13, 3) NULL,
	[ABDAT] [varchar](8) NULL,
	[ABSFZ] [numeric](13, 3) NULL,
	[POSEX] [varchar](6) NULL,
	[KDMAT] [varchar](35) NULL,
	[KBVER] [numeric](3, 0) NULL,
	[KEVER] [numeric](3, 0) NULL,
	[VKGRU] [varchar](3) NULL,
	[VKAUS] [varchar](3) NULL,
	[GRKOR] [varchar](3) NULL,
	[FMENG] [varchar](1) NULL,
	[UEBTK] [varchar](1) NULL,
	[UEBTO] [numeric](3, 1) NULL,
	[UNTTO] [numeric](3, 1) NULL,
	[FAKSP] [varchar](2) NULL,
	[ATPKZ] [varchar](1) NULL,
	[RKFKF] [varchar](1) NULL,
	[SPART] [varchar](2) NULL,
	[GSBER] [varchar](4) NULL,
	[NETWR] [numeric](15, 2) NULL,
	[WAERK] [varchar](5) NULL,
	[ANTLF] [numeric](1, 0) NULL,
	[KZTLF] [varchar](1) NULL,
	[CHSPL] [varchar](1) NULL,
	[KWMENG] [numeric](15, 3) NULL,
	[LSMENG] [numeric](15, 3) NULL,
	[KBMENG] [numeric](15, 3) NULL,
	[KLMENG] [numeric](15, 3) NULL,
	[VRKME] [varchar](3) NULL,
	[UMVKZ] [numeric](5, 0) NULL,
	[UMVKN] [numeric](5, 0) NULL,
	[BRGEW] [numeric](15, 3) NULL,
	[NTGEW] [numeric](15, 3) NULL,
	[GEWEI] [varchar](3) NULL,
	[VOLUM] [numeric](15, 3) NULL,
	[VOLEH] [varchar](3) NULL,
	[VBELV] [varchar](10) NULL,
	[POSNV] [varchar](6) NULL,
	[VGBEL] [varchar](10) NULL,
	[VGPOS] [varchar](6) NULL,
	[VOREF] [varchar](1) NULL,
	[UPFLU] [varchar](1) NULL,
	[ERLRE] [varchar](1) NULL,
	[LPRIO] [varchar](2) NULL,
	[WERKS] [varchar](4) NULL,
	[LGORT] [varchar](4) NULL,
	[VSTEL] [varchar](4) NULL,
	[ROUTE] [varchar](6) NULL,
	[STKEY] [varchar](1) NULL,
	[STDAT] [varchar](8) NULL,
	[STLNR] [varchar](8) NULL,
	[STPOS] [numeric](5, 0) NULL,
	[AWAHR] [varchar](3) NULL,
	[ERDAT] [varchar](8) NULL,
	[ERNAM] [varchar](12) NULL,
	[ERZET] [varchar](6) NULL,
	[TAXM1] [varchar](1) NULL,
	[TAXM2] [varchar](1) NULL,
	[TAXM3] [varchar](1) NULL,
	[TAXM4] [varchar](1) NULL,
	[TAXM5] [varchar](1) NULL,
	[TAXM6] [varchar](1) NULL,
	[TAXM7] [varchar](1) NULL,
	[TAXM8] [varchar](1) NULL,
	[TAXM9] [varchar](1) NULL,
	[VBEAF] [numeric](5, 2) NULL,
	[VBEAV] [numeric](5, 2) NULL,
	[VGREF] [varchar](1) NULL,
	[NETPR] [numeric](11, 2) NULL,
	[KPEIN] [numeric](5, 0) NULL,
	[KMEIN] [varchar](3) NULL,
	[SHKZG] [varchar](1) NULL,
	[SKTOF] [varchar](1) NULL,
	[MTVFP] [varchar](2) NULL,
	[SUMBD] [varchar](1) NULL,
	[KONDM] [varchar](2) NULL,
	[KTGRM] [varchar](2) NULL,
	[BONUS] [varchar](2) NULL,
	[PROVG] [varchar](2) NULL,
	[EANNR] [varchar](13) NULL,
	[PRSOK] [varchar](1) NULL,
	[BWTAR] [varchar](10) NULL,
	[BWTEX] [varchar](1) NULL,
	[XCHPF] [varchar](1) NULL,
	[XCHAR] [varchar](1) NULL,
	[LFMNG] [numeric](13, 3) NULL,
	[STAFO] [varchar](6) NULL,
	[WAVWR] [numeric](13, 2) NULL,
	[KZWI1] [numeric](13, 2) NULL,
	[KZWI2] [numeric](13, 2) NULL,
	[KZWI3] [numeric](13, 2) NULL,
	[KZWI4] [numeric](13, 2) NULL,
	[KZWI5] [numeric](13, 2) NULL,
	[KZWI6] [numeric](13, 2) NULL,
	[STCUR] [numeric](9, 5) NULL,
	[AEDAT] [varchar](8) NULL,
	[EAN11] [varchar](18) NULL,
	[FIXMG] [varchar](1) NULL,
	[PRCTR] [varchar](10) NULL,
	[MVGR1] [varchar](3) NULL,
	[MVGR2] [varchar](3) NULL,
	[MVGR3] [varchar](3) NULL,
	[MVGR4] [varchar](3) NULL,
	[MVGR5] [varchar](3) NULL,
	[KMPMG] [numeric](13, 3) NULL,
	[SUGRD] [varchar](4) NULL,
	[SOBKZ] [varchar](1) NULL,
	[VPZUO] [varchar](1) NULL,
	[PAOBJNR] [varchar](10) NULL,
	[PS_PSP_PNR] [varchar](8) NULL,
	[AUFNR] [varchar](12) NULL,
	[VPMAT] [varchar](18) NULL,
	[VPWRK] [varchar](4) NULL,
	[PRBME] [varchar](3) NULL,
	[UMREF] [float] NULL,
	[KNTTP] [varchar](1) NULL,
	[KZVBR] [varchar](1) NULL,
	[SERNR] [varchar](8) NULL,
	[OBJNR] [varchar](22) NULL,
	[ABGRS] [varchar](6) NULL,
	[BEDAE] [varchar](4) NULL,
	[CMPRE] [numeric](11, 2) NULL,
	[CMTFG] [varchar](1) NULL,
	[CMPNT] [varchar](1) NULL,
	[CMKUA] [numeric](9, 5) NULL,
	[CUOBJ] [varchar](18) NULL,
	[CUOBJ_CH] [varchar](18) NULL,
	[CEPOK] [varchar](1) NULL,
	[KOUPD] [varchar](1) NULL,
	[SERAIL] [varchar](4) NULL,
	[ANZSN] [int] NULL,
	[NACHL] [varchar](1) NULL,
	[MAGRV] [varchar](4) NULL,
	[MPROK] [varchar](1) NULL,
	[VGTYP] [varchar](1) NULL,
	[PROSA] [varchar](1) NULL,
	[UEPVW] [varchar](1) NULL,
	[KALNR] [varchar](12) NULL,
	[KLVAR] [varchar](4) NULL,
	[SPOSN] [varchar](4) NULL,
	[KOWRR] [varchar](1) NULL,
	[STADAT] [varchar](8) NULL,
	[EXART] [varchar](2) NULL,
	[PREFE] [varchar](1) NULL,
	[KNUMH] [varchar](10) NULL,
	[CLINT] [varchar](10) NULL,
	[CHMVS] [varchar](3) NULL,
	[STLTY] [varchar](1) NULL,
	[STLKN] [varchar](8) NULL,
	[STPOZ] [varchar](8) NULL,
	[STMAN] [varchar](1) NULL,
	[ZSCHL_K] [varchar](6) NULL,
	[KALSM_K] [varchar](6) NULL,
	[KALVAR] [varchar](4) NULL,
	[KOSCH] [varchar](18) NULL,
	[UPMAT] [varchar](18) NULL,
	[UKONM] [varchar](2) NULL,
	[MFRGR] [varchar](8) NULL,
	[PLAVO] [varchar](4) NULL,
	[KANNR] [varchar](35) NULL,
	[CMPRE_FLT] [float] NULL,
	[ABFOR] [varchar](2) NULL,
	[ABGES] [float] NULL,
	[J_1BCFOP] [varchar](10) NULL,
	[J_1BTAXLW1] [varchar](3) NULL,
	[J_1BTAXLW2] [varchar](3) NULL,
	[J_1BTXSDC] [varchar](2) NULL,
	[WKTNR] [varchar](10) NULL,
	[WKTPS] [varchar](6) NULL,
	[SKOPF] [varchar](18) NULL,
	[KZBWS] [varchar](1) NULL,
	[WGRU1] [varchar](18) NULL,
	[WGRU2] [varchar](18) NULL,
	[KNUMA_PI] [varchar](10) NULL,
	[KNUMA_AG] [varchar](10) NULL,
	[KZFME] [varchar](1) NULL,
	[LSTANR] [varchar](1) NULL,
	[TECHS] [varchar](12) NULL,
	[MWSBP] [numeric](13, 2) NULL,
	[BERID] [varchar](10) NULL,
	[PCTRF] [varchar](10) NULL,
	[LOGSYS_EXT] [varchar](10) NULL,
	[J_1BTAXLW3] [varchar](3) NULL,
	[J_1BTAXLW4] [varchar](3) NULL,
	[J_1BTAXLW5] [varchar](3) NULL,
	[/BEV1/SRFUND] [varchar](2) NULL,
	[/SOPROMET/KOSTL] [varchar](10) NULL,
	[/SOPROMET/LRESN] [varchar](10) NULL,
	[/SOPROMET/NOSHP] [varchar](1) NULL,
	[/SOPROMET/POSNR] [varchar](6) NULL,
	[/SOPROMET/KZLGB] [varchar](1) NULL,
	[FERC_IND] [varchar](4) NULL,
	[KOSTL] [varchar](10) NULL,
	[FONDS] [varchar](10) NULL,
	[FISTL] [varchar](16) NULL,
	[FKBER] [varchar](16) NULL,
	[GRANT_NBR] [varchar](20) NULL,
	[ZZ_SURGERY] [varchar](20) NULL,
	[ZZBOM] [varchar](1) NULL,
	[ZZ_ITEXCRPT] [varchar](1) NULL,
	[ZZ_ITEXCLLRPT] [varchar](1) NULL
) ON [PRIMARY]
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ed1].[VBFA]') AND type in (N'U'))
BEGIN
CREATE TABLE [ed1].[VBFA](
	[MANDT] [varchar](3) NOT NULL,
	[VBELV] [varchar](10) NOT NULL,
	[POSNV] [varchar](6) NOT NULL,
	[VBELN] [varchar](10) NOT NULL,
	[POSNN] [varchar](6) NOT NULL,
	[VBTYP_N] [varchar](1) NOT NULL,
	[RFMNG] [decimal](15, 3) NOT NULL,
	[MEINS] [varchar](3) NOT NULL,
	[RFWRT] [decimal](15, 2) NOT NULL,
	[WAERS] [varchar](5) NOT NULL,
	[VBTYP_V] [varchar](1) NOT NULL,
	[PLMIN] [varchar](1) NOT NULL,
	[TAQUI] [varchar](1) NOT NULL,
	[ERDAT] [varchar](8) NOT NULL,
	[ERZET] [varchar](6) NOT NULL,
	[MATNR] [varchar](18) NOT NULL,
	[BWART] [varchar](3) NOT NULL,
	[BDART] [varchar](2) NOT NULL,
	[PLART] [varchar](1) NOT NULL,
	[STUFE] [varchar](2) NOT NULL,
	[LGNUM] [varchar](3) NOT NULL,
	[AEDAT] [varchar](8) NOT NULL,
	[FKTYP] [varchar](1) NOT NULL,
	[BRGEW] [decimal](15, 3) NOT NULL,
	[GEWEI] [varchar](3) NOT NULL,
	[VOLUM] [decimal](15, 3) NOT NULL,
	[VOLEH] [varchar](3) NOT NULL,
	[FPLNR] [varchar](10) NOT NULL,
	[FPLTR] [varchar](6) NOT NULL,
	[RFMNG_FLO] [float] NOT NULL,
	[RFMNG_FLT] [float] NOT NULL,
	[VRKME] [varchar](3) NOT NULL,
	[ABGES] [float] NOT NULL,
	[SOBKZ] [varchar](1) NOT NULL,
	[SONUM] [varchar](16) NOT NULL,
	[KZBEF] [varchar](1) NOT NULL,
	[NTGEW] [decimal](13, 3) NOT NULL,
	[LOGSYS] [varchar](10) NOT NULL,
	[WBSTA] [varchar](1) NOT NULL,
	[CMETH] [varchar](1) NOT NULL,
	[MJAHR] [varchar](4) NOT NULL
) ON [PRIMARY]
END
GO

SET ANSI_PADDING OFF
GO


